import styles from "@/styles/globals.module.css"
import Head from "next/head"
import Image from "next/image"
import { Inter } from "@next/font/google"
import {useEffect, useState} from "react";

import Product from "../components/Product";
import Footer from "../components/Footer";
import Layout from "../components/Layout";

export default function Home({ products, categories }) {
  const [phrase,setPhrase] = useState('');

  const findCategory = (id) => {
    const found = categories.categories?.find(element => element._id == id)?.categoryName;
    return found;
  };

  const categoriesNames = [...products.products.map(p => findCategory(p.categoryId))];
  
  console.log("gh: ", categoriesNames);
  console.log("ghh: ", categories.categories);

  // if (phrase) {
  //   products = products.filter(p => p.name.toLowerCase().includes(phrase));
  // }

  return (
    <Layout>
      <input value={phrase} onChange={e => setPhrase(e.target.value)} type="text" placeholder="Search for products..." className="bg-gray-200 w-full py-2 px-4 rounded-xl"/>
      
      <div>
        {categories.categories.map(category => (
          <div key={category.categoryId}>
            {products.products.find(p => p.categoryId === category._id) && (
              <div>
                <h2 className="text-2xl py-5 capitalize">{category.categoryName}</h2>
                <div className="flex -mx-5 overflow-x-scroll snap-x scrollbar-hide">
                  {products.products.filter(p => p.categoryId === category._id).map(productInfo => (
                    <div key={productInfo._id} className="px-5 snap-start">
                      <Product {...productInfo} />
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>

    </Layout>
  )
}



export async function getServerSideProps() {
  // Fetch data from external API
  const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL;
  console.log("products: ",  BASE_URL);

  const resProducts = await fetch(`${BASE_URL}/products/storefront`);
  const resCategories = await fetch(`${BASE_URL}/categories`);

  const products = await resProducts.json();
  const categories = await resCategories.json();

  return { props: { products, categories } };
}



// export default function Home() {
//   return (
//     <>
//     <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <meta name="viewport" content="width=device-width, initial-scale=1" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//     </>
//   )
// }
